
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author APRENDIZ
 */
public class Formulario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTtulo = new javax.swing.JLabel();
        jlblIDProducto = new javax.swing.JLabel();
        jtxtIdProducto = new javax.swing.JTextField();
        jlblPlaca = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JTextField();
        jlblModelo = new javax.swing.JLabel();
        jtxtModelo = new javax.swing.JTextField();
        jlblMarca = new javax.swing.JLabel();
        jlblCilindraje = new javax.swing.JLabel();
        jlblCCpropietario = new javax.swing.JLabel();
        jlblNombre = new javax.swing.JLabel();
        jlbtelefono = new javax.swing.JLabel();
        lblFingreso = new javax.swing.JLabel();
        jtxtCilindraje = new javax.swing.JTextField();
        jtxtMarca = new javax.swing.JTextField();
        jtxtccPropietario = new javax.swing.JTextField();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jBtnGuardar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnBorra = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jlblEstado = new javax.swing.JLabel();
        jCboxEstado = new javax.swing.JComboBox<>();
        jBtnbuscar = new javax.swing.JButton();

        jlblTtulo.setBackground(new java.awt.Color(0, 0, 0));
        jlblTtulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlblTtulo.setText("Registrar Vehiculo");
        jlblTtulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblIDProducto.setText("ID PRODUCTO");
        jlblIDProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtIdProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdProductoActionPerformed(evt);
            }
        });
        jtxtIdProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIdProductoKeyTyped(evt);
            }
        });

        jlblPlaca.setText("PLACA");
        jlblPlaca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtPlaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPlacaKeyTyped(evt);
            }
        });

        jlblModelo.setText("MODELO");
        jlblModelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtModelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblMarca.setText("MARCA");
        jlblMarca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblCilindraje.setText("CILINDRAJE");
        jlblCilindraje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblCCpropietario.setText("CC PROPIETARIO");
        jlblCCpropietario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblNombre.setText("NOMBRE");
        jlblNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlbtelefono.setText("TELEFONO");
        jlbtelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFingreso.setText("FECHA DE INGRESO");
        lblFingreso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtCilindraje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtMarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtxtccPropietario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtccPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtccPropietarioKeyTyped(evt);
            }
        });

        jtxtTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });

        jtxtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });

        jBtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/guardar-el-archivo.png"))); // NOI18N
        jBtnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/editar.png"))); // NOI18N
        jBtnEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnBorra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/basura.png"))); // NOI18N
        jBtnBorra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorraActionPerformed(evt);
            }
        });

        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/salida.png"))); // NOI18N
        jBtnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jlblEstado.setText("ESTADO");
        jlblEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECIONE-", "ON", "OFF" }));

        jBtnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/buscar.png"))); // NOI18N
        jBtnbuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCCpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtccPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFingreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jBtnBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jlblTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jlblTtulo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jtxtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jlblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jtxtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jtxtCilindraje, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCCpropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jlblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jtxtccPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlbtelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdProductoActionPerformed

    private void jtxtIdProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIdProductoKeyTyped
        // TODO add your handling code here:
        int limite=10;
        if(jtxtIdProducto.getText().length()==limite)
        {
            evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar()))
        {
            getToolkit().beep();
            evt.consume();
        }
        
        
    }//GEN-LAST:event_jtxtIdProductoKeyTyped

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jtxtccPropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtccPropietarioKeyTyped
        // TODO add your handling code here:
        int limite=10;
        if(jtxtccPropietario.getText().length()==limite)
        {
            evt.consume();
        }
        if(!Character.isDigit(evt.getKeyChar()))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxtccPropietarioKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        // TODO add your handling code here:
        int limite=10;
        if(jtxtTelefono.getText().length()==limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPlacaKeyTyped
        // TODO add your handling code here:
        int limite=6;
        if(jtxtPlaca.getText().length()==limite)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPlacaKeyTyped

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        insertar();
        
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jBtnBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorraActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_jBtnBorraActionPerformed

    private void jBtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnbuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_jBtnbuscarActionPerformed
    
    public void insertar()
    {
        conexion conexion1; //variable conexion
        conexion1  = new conexion();//conexion
        try
        {   
            //java.util.Date date = (java.util.Date)jDateChooser1.getDate();
            Date date = (Date) jDateChooser1.getDate();
            long d1 = date.getTime();
            java.sql.Date Fecha = new java.sql.Date(d1);
            
            Connection Reconectar;//conector
            Reconectar=conexion1.conectar();//llamar la funcion conectar
            PreparedStatement pps;
            String sql;
            
            sql = "INSERT INTO tblautomoviles (ID,Placa,Modelo,Marca,Cilindraje,IDP,NombreP,Telefono,FechaIngreso,Estado) VALUES (?,?,?,?,?,?,?,?,?,?) ";
            pps=Reconectar.prepareStatement(sql);
            pps.setString(1,jtxtIdProducto.getText().trim());
            pps.setString(2,jtxtPlaca.getText().trim());
            pps.setString(3,jtxtModelo.getText().trim());
            pps.setString(4,jtxtMarca.getText().trim());
            pps.setString(5,jtxtCilindraje.getText().trim());
            pps.setString(6,jtxtccPropietario.getText().trim());
            pps.setString(7,jtxtNombre.getText().trim());
            pps.setString(8,jtxtTelefono.getText().trim());
            pps.setDate(9, Fecha);
            pps.setString(10,jCboxEstado.getSelectedItem().toString());
            pps.execute();
            pps.close();
            
            JOptionPane.showMessageDialog(null,"guardado con exito");
        }
        catch(SQLException e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
        
    }
    public void editar()
    {
        Date date = (Date) jDateChooser1.getDate();
        long d1 = date.getTime();
        java.sql.Date Fecha = new java.sql.Date(d1);
        
        conexion conexion1;
        conexion1 = new conexion();
        try
        {
            Connection Reconectar;
            Reconectar=conexion1.conectar();
            PreparedStatement pps;
            String sql;
            sql= "UPDATE tblautomoviles SET Placa=?,Modelo=?,Marca=?,Cilindraje=?,IDP=?,NombreP=?,Telefono=?,FechaIngreso=?,Estado=? WHERE ID=?";
            pps=Reconectar.prepareStatement(sql);
            pps.setString(1,jtxtPlaca.getText().trim());
            pps.setString(2,jtxtModelo.getText().trim());
            pps.setString(3,jtxtMarca.getText().trim());
            pps.setString(4,jtxtCilindraje.getText().trim());
            pps.setString(5,jtxtccPropietario.getText().trim());
            pps.setString(6,jtxtNombre.getText().trim());
            pps.setString(7,jtxtTelefono.getText().trim());
            pps.setDate(8, Fecha);
            pps.setString(9,jCboxEstado.getSelectedItem().toString());
            pps.setString(10,jtxtIdProducto.getText().trim());
            
            pps.execute();
            pps.close();
            JOptionPane.showMessageDialog(null,"Modificados con exito");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    public void eliminar()
    {
        conexion conexion1;
        conexion1 = new conexion();
        try
        {
            Connection Reconectar;//conector
            Reconectar=conexion1.conectar();
            PreparedStatement pps;
            String sql;
            sql="Delete from tblautomoviles where ID=?";
            pps=Reconectar.prepareStatement(sql);
            pps.setString(1,jtxtIdProducto.getText().trim());
            pps.execute();
            pps.close();
            JOptionPane.showMessageDialog(null,"Eliminado con exitoS");
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void buscar()
    {
        conexion conexion1;
        conexion1 = new conexion();
        try
        {
            Connection Reconectar;//conector
            Reconectar=conexion1.conectar();
            PreparedStatement pps;
            ResultSet rs;
            pps = Reconectar.prepareStatement("select * from tblautomoviles where ID = ?");
            pps.setString(1,this.jtxtIdProducto.getText().trim());
            
            rs = pps.executeQuery();
            
            if(rs.next())
            {
                this.jtxtIdProducto.setText(rs.getString("Id"));
                this.jtxtPlaca.setText(rs.getString("Placa"));
                this.jtxtModelo.setText(rs.getString("Modelo"));
                this.jtxtMarca.setText(rs.getString("Marca"));
                this.jtxtCilindraje.setText(rs.getString("Cilindraje"));
                this.jtxtccPropietario.setText(rs.getString("IDP"));
                this.jtxtNombre.setText(rs.getString("NombreP"));
                this.jtxtTelefono.setText(rs.getString("Telefono"));
                this.jDateChooser1.setDate(rs.getDate("Fecha"));
                
            }    
        }catch(SQLException e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBorra;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnbuscar;
    private javax.swing.JComboBox<String> jCboxEstado;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jlblCCpropietario;
    private javax.swing.JLabel jlblCilindraje;
    private javax.swing.JLabel jlblEstado;
    private javax.swing.JLabel jlblIDProducto;
    private javax.swing.JLabel jlblMarca;
    private javax.swing.JLabel jlblModelo;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JLabel jlblPlaca;
    private javax.swing.JLabel jlblTtulo;
    private javax.swing.JLabel jlbtelefono;
    private javax.swing.JTextField jtxtCilindraje;
    private javax.swing.JTextField jtxtIdProducto;
    private javax.swing.JTextField jtxtMarca;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField jtxtccPropietario;
    private javax.swing.JLabel lblFingreso;
    // End of variables declaration//GEN-END:variables
}
